# Generated by Django 3.2.8 on 2022-01-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('port', models.IntegerField(default=50050)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
