# Generated by Django 3.2.8 on 2022-01-04 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('note', models.CharField(max_length=100)),
                ('charset', models.CharField(max_length=100)),
                ('listener', models.CharField(max_length=100)),
                ('internal', models.CharField(max_length=45)),
                ('external', models.CharField(max_length=45)),
                ('computer', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=45)),
                ('process', models.CharField(max_length=100)),
                ('pid', models.CharField(max_length=20)),
                ('barch', models.CharField(max_length=20)),
                ('os', models.CharField(max_length=20)),
                ('ver', models.CharField(max_length=20)),
                ('build', models.CharField(max_length=20)),
                ('arch', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=100)),
                ('opened', models.DateTimeField()),
                ('team_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobalt_strike_monitor.teamserver')),
            ],
        ),
    ]
