# Generated by Django 4.0.1 on 2022-01-05 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0002_beacon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('when', models.DateTimeField()),
                ('type', models.CharField(max_length=20)),
                ('data', models.CharField(max_length=100)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobalt_strike_monitor.beacon')),
                ('team_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobalt_strike_monitor.teamserver')),
            ],
        ),
    ]
