# Generated by Django 4.0.1 on 2022-01-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0003_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='tactic',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
