# Generated by Django 4.0.1 on 2022-01-05 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0004_archive_tactic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='bid',
            new_name='beacon',
        ),
        migrations.CreateModel(
            name='BeaconLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('when', models.DateTimeField()),
                ('type', models.CharField(max_length=20)),
                ('data', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100, null=True)),
                ('beacon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobalt_strike_monitor.beacon')),
                ('team_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobalt_strike_monitor.teamserver')),
            ],
        ),
    ]
