# Generated by Django 4.0.1 on 2022-01-06 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0005_rename_bid_archive_beacon_beaconlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listener',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('proxy', models.CharField(max_length=100)),
                ('payload', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('althost', models.CharField(max_length=100)),
                ('strategy', models.CharField(max_length=100)),
                ('beacons', models.CharField(max_length=100)),
                ('bindto', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('team_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobalt_strike_monitor.teamserver')),
            ],
        ),
    ]
