# Generated by Django 4.0.1 on 2022-01-06 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0006_listener'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacon',
            name='listener',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobalt_strike_monitor.listener'),
        ),
    ]
