# Generated by Django 4.0.1 on 2022-01-06 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0007_alter_beacon_listener'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='beacon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cobalt_strike_monitor.beacon'),
        ),
    ]
