# Generated by Django 4.0.1 on 2022-01-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0008_alter_archive_beacon'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamserver',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
