# Generated by Django 4.0.1 on 2022-01-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0009_teamserver_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamserver',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teamserver',
            name='hostname',
            field=models.CharField(max_length=100, verbose_name='Hostname or IP'),
        ),
    ]
