# Generated by Django 4.0.1 on 2022-01-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0010_alter_teamserver_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listener',
            name='maxretry',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
