# Generated by Django 4.0.2 on 2022-02-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0011_listener_maxretry'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamserver',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
