# Generated by Django 4.0.3 on 2022-03-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0012_teamserver_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('realm', models.CharField(max_length=100)),
                ('added', models.DateTimeField()),
                ('source', models.CharField(max_length=100)),
            ],
        ),
    ]
