# Generated by Django 4.0.3 on 2022-03-30 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0013_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='team_server',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cobalt_strike_monitor.teamserver'),
            preserve_default=False,
        ),
    ]
