# Generated by Django 4.0.3 on 2022-04-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0014_credential_team_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='beacon',
            name='session',
            field=models.CharField(default='beacon', max_length=50),
            preserve_default=False,
        ),
    ]
