# Generated by Django 4.0.4 on 2022-05-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0015_beacon_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='beacon',
            name='last',
            field=models.DateTimeField(null=True),
        ),
    ]
