# Generated by Django 4.0.4 on 2022-05-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0016_beacon_last'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeaconExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beacon_id', models.IntegerField(null=True)),
                ('computer', models.CharField(max_length=100, null=True)),
                ('user', models.CharField(max_length=100, null=True)),
                ('process', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
