# Generated by Django 4.0.4 on 2022-06-08 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0017_beaconexclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeaconPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_checkin', models.DateTimeField()),
                ('last_checkin', models.DateTimeField()),
                ('beacon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobalt_strike_monitor.beacon')),
            ],
        ),
    ]
