# Generated by Django 4.0.4 on 2022-06-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0018_beaconpresence'),
    ]

    operations = [
        migrations.AddField(
            model_name='beaconpresence',
            name='sleep_jitter',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beaconpresence',
            name='sleep_seconds',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
