# Generated by Django 4.0.4 on 2022-06-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0019_beaconpresence_sleep_jitter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beaconlog',
            name='data',
            field=models.TextField(),
        ),
    ]
