# Generated by Django 4.0.5 on 2022-06-21 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0020_alter_beaconlog_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('size', models.IntegerField()),
                ('path', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=100)),
                ('beacon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobalt_strike_monitor.beacon')),
                ('team_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobalt_strike_monitor.teamserver')),
            ],
        ),
    ]
