# Generated by Django 4.0.5 on 2022-07-11 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0022_beacon_parent_beacon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacon',
            name='listener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cobalt_strike_monitor.listener'),
        ),
    ]
