# Generated by Django 4.2.1 on 2023-05-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0023_alter_beacon_listener'),
    ]

    operations = [
        migrations.AddField(
            model_name='beaconexclusion',
            name='external',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='beaconexclusion',
            name='internal',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
