# Generated by Django 5.1.7 on 2025-03-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0024_beaconexclusion_external_beaconexclusion_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='listener',
            name='guards',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='listener',
            name='localonly',
            field=models.BooleanField(default=False),
        ),
    ]
