# Generated by Django 5.1.7 on 2025-03-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0025_listener_guards_listener_localonly'),
    ]

    operations = [
        migrations.AddField(
            model_name='beaconlog',
            name='output_job',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='beaconlog',
            name='type',
            field=models.CharField(max_length=25),
        ),
    ]
