# Generated by Django 5.1.7 on 2025-03-13 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0026_beaconlog_output_job_alter_beaconlog_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='archive',
            name='cs_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cobalt_strike_monitor.csaction'),
        ),
        migrations.AddField(
            model_name='beaconlog',
            name='cs_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cobalt_strike_monitor.csaction'),
        ),
    ]
