# Generated by Django 5.1.7 on 2025-03-13 14:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0027_csaction_archive_cs_action_beaconlog_cs_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='csaction',
            name='beacon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cobalt_strike_monitor.beacon'),
        ),
        migrations.AddField(
            model_name='csaction',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
