# Generated by Django 5.1.7 on 2025-03-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0028_csaction_beacon_csaction_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='csaction',
            name='accept_output',
            field=models.BooleanField(default=True),
        ),
    ]
