# Generated by Django 5.1.7 on 2025-03-17 20:00

from django.db import migrations

from cobalt_strike_monitor.signals import beaconlog_action_correlator, archive_action_correlator


def forwards(apps, schema_editor):
    if schema_editor.connection.alias != "default":
        return

    BeaconLog = apps.get_model("cobalt_strike_monitor", "BeaconLog")
    for log in BeaconLog.objects.filter(cs_action__isnull=True).prefetch_related("beacon").all():
        beaconlog_action_correlator(None, log)
        log.save()

    Archive = apps.get_model("cobalt_strike_monitor", "Archive")
    for archive in Archive.objects.filter(cs_action__isnull=True).prefetch_related("beacon").all():
        archive_action_correlator(None, archive)
        archive.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0029_csaction_accept_output'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.RunSQL(migrations.RunSQL.noop, [
            ("update cobalt_strike_monitor_beaconlog set cs_action_id = NULL where 1=1;"),
            ("update cobalt_strike_monitor_archive set cs_action_id = NULL where 1=1;"),
            ("delete from cobalt_strike_monitor_csaction where 1=1;")]),
    ]
