# Generated by Django 3.2.8 on 2021-10-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0002_task_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackSubTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitre_id', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AttackTactic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitre_id', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=50)),
                ('shortname', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='AttackTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitre_id', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50)),
                ('tactics', models.ManyToManyField(to='event_tracker.AttackTactic')),
            ],
        ),
    ]
