# Generated by Django 3.2.8 on 2021-10-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0003_attacksubtechnique_attacktactic_attacktechnique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attacksubtechnique',
            name='mitre_id',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='attacktactic',
            name='mitre_id',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='attacktechnique',
            name='mitre_id',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
