# Generated by Django 3.2.8 on 2021-10-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0004_auto_20211020_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortNameManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
