# Generated by Django 3.2.8 on 2021-10-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0005_shortnamemanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attacktactic',
            name='shortname',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
