# Generated by Django 3.2.8 on 2021-10-20 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0008_attacksubtechnique_parent_technique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='mitre_ref',
        ),
        migrations.AddField(
            model_name='event',
            name='mitre_attack_subtechnique',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='event_tracker.attacksubtechnique'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='mitre_attack_tactic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='event_tracker.attacktactic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='mitre_attack_technique',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='event_tracker.attacktechnique'),
            preserve_default=False,
        ),
    ]
