# Generated by Django 3.2.8 on 2021-10-21 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0010_auto_20211020_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attacksubtechnique',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='attacktactic',
            options={'ordering': ['step']},
        ),
        migrations.AlterModelOptions(
            name='attacktechnique',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='attacktactic',
            name='step',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='mitre_attack_subtechnique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='event_tracker.attacksubtechnique'),
        ),
        migrations.AlterField(
            model_name='event',
            name='mitre_attack_tactic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='event_tracker.attacktactic'),
        ),
        migrations.AlterField(
            model_name='event',
            name='mitre_attack_technique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='event_tracker.attacktechnique'),
        ),
    ]
