# Generated by Django 3.2.8 on 2021-10-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0011_auto_20211021_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='detected',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='worked',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
