# Generated by Django 3.2.8 on 2021-11-09 14:17

from django.conf import settings
from django.contrib.auth.models import User
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_tracker', '0015_alter_event_outcome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='operator'
        ),
        migrations.AddField(
            model_name='event',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event_tracker.task'),
        ),
    ]
