# Generated by Django 3.2.8 on 2021-12-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0017_alter_event_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='prevented',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),

        migrations.RunSQL(
            sql="UPDATE event_tracker_event SET prevented=not(worked);",
            reverse_sql="UPDATE event_tracker_event SET worked=not(prevented);"
        ),

        migrations.RemoveField(
            model_name='event',
            name='worked',
        ),
    ]
