# Generated by Django 4.0.1 on 2022-01-25 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0018_auto_20211210_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('size', models.IntegerField()),
                ('md5_hash', models.CharField(max_length=32)),
                ('sha1_hash', models.CharField(max_length=40)),
                ('sha256_hash', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='FileDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=1000, null=True)),
                ('removed', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_tracker.event')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_tracker.file')),
            ],
        ),
    ]
