# Generated by Django 4.0.1 on 2022-01-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0019_file_filedistribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='md5_hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='sha1_hash',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='sha256_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='filedistribution',
            name='removed',
            field=models.BooleanField(default=False, verbose_name='Removed from Target'),
        ),
    ]
