# Generated by Django 4.0.1 on 2022-01-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0020_alter_file_md5_hash_alter_file_sha1_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='md5_hash',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='MD5 Hash'),
        ),
        migrations.AlterField(
            model_name='file',
            name='sha1_hash',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='SHA1 Hash'),
        ),
        migrations.AlterField(
            model_name='file',
            name='sha256_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='SHA256 Hash'),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
