# Generated by Django 4.0.2 on 2022-02-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0021_alter_file_filename_alter_file_md5_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('source_time', models.DateTimeField()),
                ('system', models.CharField(max_length=200)),
                ('account', models.CharField(max_length=200)),
                ('secret', models.CharField(max_length=200)),
                ('purpose', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
