# Generated by Django 4.0.2 on 2022-02-18 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0012_teamserver_active'),
        ('event_tracker', '0023_alter_credential_source_alter_credential_source_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMappingCsBeacon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beacon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobalt_strike_monitor.beacon')),
                ('connection_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_tracker.event')),
            ],
        ),
    ]
