# Generated by Django 4.0.3 on 2022-03-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0024_eventmappingcsbeacon'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='hash',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='timestamp_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='purpose',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='secret',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
