# Generated by Django 4.0.4 on 2022-05-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0028_credential_hash_type_alter_userpreferences_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='hash_type',
            field=models.IntegerField(blank=True, choices=[(1000, 'NTLM (1000)'), (5600, 'NetNTLMv2 (5600)')], help_text='The hashcat module number for the hash', null=True),
        ),
    ]
