# Generated by Django 4.0.4 on 2022-06-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0030_webhook'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='context',
            constraint=models.UniqueConstraint(fields=('process', 'user', 'host'), name='unique context'),
        ),
    ]
