# Generated by Django 4.0.4 on 2022-06-13 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0020_alter_beaconlog_data'),
        ('event_tracker', '0031_context_unique context'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeaconReconnectionWatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beacon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobalt_strike_monitor.beacon')),
            ],
        ),
    ]
