# Generated by Django 4.0.5 on 2022-06-24 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobalt_strike_monitor', '0021_download'),
        ('event_tracker', '0032_beaconreconnectionwatcher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventMappingCsBeacon',
            new_name='EventMapping',
        ),
    ]
