# Generated by Django 4.0.5 on 2022-06-24 09:19
from django.contrib.contenttypes.models import ContentType
from django.db import migrations, models

from cobalt_strike_monitor.models import Beacon

def find_beacon_ct_pk():
    return ContentType.objects.get_for_model(Beacon).pk

class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0034_rename_connection_event_eventmapping_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmapping',
            name='object_type',
            field=models.PositiveIntegerField(default=find_beacon_ct_pk),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventmapping',
            name='object_id',
            field=models.IntegerField(),
        ),
    ]
