# Generated by Django 4.0.5 on 2022-06-24 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0036_alter_eventmapping_object_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmapping',
            old_name='object_type',
            new_name='content_type',
        ),
    ]
