# Generated by Django 4.0.5 on 2022-07-14 10:09

from django.db import migrations, models

def consolidate_files(apps, schema_editor):
    FileDistribution = apps.get_model("event_tracker", "FileDistribution")
    File = apps.get_model("event_tracker", "File")

    files_to_process = list(File.objects.all())

    # Need to work through our list of files to process rather than use a regular for loop as the thing we're iterating
    # over will change within the iteration
    while files_to_process:
        file = files_to_process.pop()
        equivalent_files = File.objects.filter(filename=file.filename, md5_hash=file.md5_hash, size=file.size).exclude(pk=file.pk)
        FileDistribution.objects.filter(file__in=equivalent_files).update(file=file)

        for equivalent_file in equivalent_files:
            files_to_process.remove(equivalent_file)
        equivalent_files.delete()

class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('event_tracker', '0039_fix_file_paths'),
    ]

    operations = [
        migrations.RunPython(consolidate_files, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('filename', 'size', 'md5_hash'), name='unique file'),
        ),
    ]
