# Generated by Django 4.0.6 on 2022-08-05 13:02

from django.db import migrations, models
import event_tracker.models


class Migration(migrations.Migration):

    replaces = [('event_tracker', '0041_bloodhoundserver'), ('event_tracker', '0042_alter_bloodhoundserver_url'), ('event_tracker', '0043_rename_url_bloodhoundserver_neo4j_connection_url_and_more')]

    dependencies = [
        ('event_tracker', '0040_file_unique file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodhoundServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neo4j_connection_url', event_tracker.models.Neo4jURLField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('neo4j_browser_url', models.URLField(default='https://example.com')),
            ],
        ),
    ]
