# Generated by Django 4.0.6 on 2022-08-05 11:53

from django.db import migrations
import event_tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0041_bloodhoundserver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodhoundserver',
            name='url',
            field=event_tracker.models.Neo4jURLField(),
        ),
    ]
