# Generated by Django 4.0.6 on 2022-08-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0042_alter_bloodhoundserver_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodhoundserver',
            old_name='url',
            new_name='neo4j_connection_url',
        ),
        migrations.AddField(
            model_name='bloodhoundserver',
            name='neo4j_browser_url',
            field=models.URLField(default='https://example.com'),
            preserve_default=False,
        ),
    ]
