# Generated by Django 4.1 on 2022-09-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0041_bloodhoundserver_squashed_0043_rename_url_bloodhoundserver_neo4j_connection_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bloodhoundserver',
            name='neo4j_browser_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='code',
            field=models.CharField(help_text='The shorthand code used to refer to the task internally', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(help_text='The last day of authorised activity on the task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(help_text='The name of the task', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(help_text='The first day of authorised activity on the task'),
        ),
    ]
