# Generated by Django 4.1.2 on 2022-10-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0044_event_starred_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='hash_type',
            field=models.IntegerField(blank=True, choices=[(1000, 'NTLM (1000)'), (3000, 'LM (3000)'), (5600, 'NetNTLMv2 (5600)'), (13100, 'Kerberos_5_TGSREP_RC4 (13100)'), (19600, 'Kerberos_5_TGSREP_AES128 (19600)'), (19700, 'Kerberos_5_TGSREP_AES256 (19700)')], help_text='The hashcat module number for the hash', null=True),
        ),
        migrations.AddIndex(
            model_name='credential',
            index=models.Index(fields=['hash'], name='event_track_hash_441483_idx'),
        ),
    ]
