# Generated by Django 4.1.3 on 2022-11-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0045_alter_credential_hash_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='detected',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
