# Generated by Django 4.1.3 on 2022-11-21 14:15

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('event_tracker', '0046_alter_event_detected'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='event',
            name='detected',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No'), (None, 'Unknown')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='prevented',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
