# Generated by Django 4.1.3 on 2022-11-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0048_attacksubtechnique_detection_advice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='complexity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddIndex(
            model_name='credential',
            index=models.Index(fields=['account', 'hash'], name='event_track_account_0ca3dd_idx'),
        ),
        migrations.AddIndex(
            model_name='credential',
            index=models.Index(fields=['system', 'account'], name='event_track_system_61915a_idx'),
        ),
    ]
