# Generated by Django 4.1.5 on 2023-01-10 17:05

from django.db import migrations
from django.contrib.auth.management import create_permissions
from django.apps import apps

APPS = [
    'event_tracker'
]


def create_applications_permissions():
    for app in APPS:
        app_config = apps.get_app_config(app)
        create_permissions(app_config)


def create_blueteam_role(apps, schema_editor):
    create_applications_permissions()  # Ensure values exist in DB to reference.
                                       # Not normally made by Django until after migration via a 'post_migrate' signal.

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    newgroup = Group(name="Client Blue Team")
    newgroup.save()

    newgroup.permissions.add(Permission.objects.get(codename="view_attacksubtechnique", content_type__app_label="event_tracker"))
    newgroup.permissions.add(Permission.objects.get(codename="view_attacktactic", content_type__app_label="event_tracker"))
    newgroup.permissions.add(Permission.objects.get(codename="view_attacktechnique", content_type__app_label="event_tracker"))
    newgroup.permissions.add(Permission.objects.get(codename="view_context", content_type__app_label="event_tracker"))
    newgroup.permissions.add(Permission.objects.get(codename="view_event", content_type__app_label="event_tracker"))
    newgroup.permissions.add(Permission.objects.get(codename="view_file", content_type__app_label="event_tracker"))
    newgroup.permissions.add(Permission.objects.get(codename="view_filedistribution", content_type__app_label="event_tracker"))
    newgroup.permissions.add(Permission.objects.get(codename="view_task", content_type__app_label="event_tracker"))
    newgroup.save()


def delete_blueteam_role(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name="Client Blue Team").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0049_credential_complexity_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(create_blueteam_role, delete_blueteam_role),
    ]
