# Generated by Django 4.1.5 on 2023-01-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0050_auto_20230110_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
