# Generated by Django 4.1.5 on 2023-01-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0051_credential_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('timestamp_end', models.DateTimeField(blank=True, null=True)),
                ('operator', models.CharField(max_length=256)),
                ('source_process', models.CharField(max_length=100)),
                ('source_user', models.CharField(max_length=100)),
                ('source_host', models.CharField(max_length=100)),
                ('target_process', models.CharField(max_length=100)),
                ('target_user', models.CharField(max_length=100)),
                ('target_host', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('mitre_tactic', models.CharField(max_length=6)),
                ('mitre_technique', models.CharField(max_length=9)),
            ],
        ),
    ]
