# Generated by Django 4.1.5 on 2023-01-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0052_importedevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedevent',
            name='mitre_tactic',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='importedevent',
            name='mitre_technique',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
