# Generated by Django 4.1.7 on 2023-02-23 13:33

from django.db import migrations, models

def migrate_detect(apps, schema_editor):
    Event = apps.get_model('event_tracker', 'Event')
    for row in Event.objects.all():
        if row.detected is None:
            row.new_detected = 'UNK'
        else:
            row.new_detected = 'FUL' if row.detected else 'NEG'
        row.save(update_fields=['new_detected'])

def migrate_prevent(apps, schema_editor):
    Event = apps.get_model('event_tracker', 'Event')
    for row in Event.objects.all():
        row.new_prevented = 'FUL' if row.prevented else 'NEG'
        row.save(update_fields=['new_prevented'])


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0054_importedevent_additional_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='new_detected',
            field=models.CharField(choices=[('UNK', 'Unknown'), ('NEG', 'Not Detected'), ('PAR', 'Partially Detected'), ('FUL', 'Fully Detected')], default='UNK', max_length=3),
        ),
        migrations.AddField(
            model_name='event',
            name='new_prevented',
            field=models.CharField(choices=[('NEG', 'Not Prevented'), ('PAR', 'Partially Prevented'), ('FUL', 'Fully Prevented')], default='NEG', max_length=3),
        ),
        migrations.RunPython(migrate_detect, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(migrate_prevent, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='event',
            name='detected'
        ),
        migrations.RemoveField(
            model_name='event',
            name='prevented'
        ),
        migrations.RenameField(
            model_name='event',
            old_name='new_detected',
            new_name='detected'
        ),
        migrations.RenameField(
            model_name='event',
            old_name='new_prevented',
            new_name='prevented'
        ),
    ]
