# Generated by Django 4.1.7 on 2023-04-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0059_alter_credential_hash_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='credential',
            index=models.Index(fields=['secret', 'hash'], name='event_track_secret_94eeab_idx'),
        ),
    ]
