# Generated by Django 4.1.7 on 2023-04-07 19:26

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('event_tracker', '0060_credential_event_track_secret_94eeab_idx'),
    ]

    operations = [
        migrations.RunSQL('pragma journal_mode=wal', 'pragma journal_mode=delete'),
        migrations.RunSQL('pragma synchronous=normal', 'pragma synchronous=full'),
    ]
