# Generated by Django 4.1.7 on 2023-04-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0061_sqlite_wal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='account',
            field=models.CharField(db_collation='nocase', max_length=200),
        ),
        migrations.AlterField(
            model_name='credential',
            name='hash',
            field=models.CharField(blank=True, db_collation='nocase', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='system',
            field=models.CharField(blank=True, db_collation='nocase', max_length=200, null=True),
        ),
    ]
