# Generated by Django 4.1.7 on 2023-04-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0062_alter_credential_account_alter_credential_hash_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='credential',
            unique_together={('system', 'account', 'hash', 'hash_type')},
        ),
    ]
