# Generated by Django 4.2 on 2023-05-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0064_importedevent_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='char_mask',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='char_mask_effort',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='structure',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
