# Generated by Django 4.2 on 2023-05-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0065_credential_char_mask_credential_char_mask_effort_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='char_mask_effort',
            field=models.PositiveBigIntegerField(default=None, null=True),
        ),
    ]
