# Generated by Django 4.2 on 2023-05-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0066_alter_credential_char_mask_effort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='hash',
            field=models.CharField(blank=True, db_collation='nocase', max_length=5500, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='purpose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
