# Generated by Django 4.2.2 on 2023-06-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0068_auto_20230523_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='haveibeenpwned_count',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
