# Generated by Django 4.2.3 on 2023-07-28 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0069_credential_haveibeenpwned_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='source_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
