# Generated by Django 4.2.5 on 2023-09-15 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0070_alter_credential_source_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='raw_evidence',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='account',
            field=models.CharField(db_collation='nocase', help_text='The username, without any system prefix or suffix', max_length=200),
        ),
        migrations.AlterField(
            model_name='credential',
            name='hash',
            field=models.CharField(blank=True, db_collation='nocase', help_text='A hashed version of the secret, in a form usable by hashcat', max_length=5500, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='purpose',
            field=models.CharField(blank=True, help_text='What the credential is used for', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='secret',
            field=models.CharField(blank=True, help_text='The password, or API key etc', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='source',
            field=models.CharField(blank=True, help_text='The tool or technique which yeilded the hash or secret', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='source_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Timestamp for when the hash or secret was obtained from the source or imported into Stepping Stones', null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='system',
            field=models.CharField(blank=True, db_collation='nocase', help_text='The scope of the account, i.e. the name of the domain or host it applies to', max_length=200, null=True),
        ),
    ]
