# Generated by Django 4.2.5 on 2023-10-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0072_auto_20230915_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='detected',
            field=models.CharField(choices=[('UNK', 'Unknown'), ('NEG', 'Not Detected'), ('PAR', 'Partially Detected'), ('FUL', 'Fully Detected'), ('N/A', 'Not Applicable')], default='UNK', max_length=3),
        ),
        migrations.AlterField(
            model_name='event',
            name='prevented',
            field=models.CharField(choices=[('NEG', 'Not Prevented'), ('PAR', 'Partially Prevented'), ('FUL', 'Fully Prevented'), ('N/A', 'Not Applicable')], default='NEG', max_length=3),
        ),
    ]
