# Generated by Django 4.2.5 on 2023-10-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0073_alter_event_detected_alter_event_prevented'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='detected',
            field=models.CharField(choices=[('N/A', 'Not Applicable'), ('UNK', 'Unknown'), ('NEG', 'No Trace'), ('PAR', 'Event Recorded'), ('FUL', 'Alert Raised')], default='UNK', max_length=3),
        ),
        migrations.AlterField(
            model_name='event',
            name='prevented',
            field=models.CharField(choices=[('N/A', 'Not Applicable'), ('NEG', 'Not Prevented'), ('PAR', 'Manual Intervention'), ('FUL', 'Blocked as Standard')], default='NEG', max_length=3),
        ),
    ]
