# Generated by Django 4.2.6 on 2023-11-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0074_alter_event_detected_alter_event_prevented'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='cracking_parameters',
            field=models.CharField(blank=True, help_text='The parameters used to crack the hash', max_length=500, null=True),
        ),
    ]
