# Generated by Django 4.2.7 on 2023-12-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0075_credential_cracking_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='bh_sync_done',
            field=models.BooleanField(default=False),
        ),
    ]
