# Generated by Django 4.2.7 on 2023-12-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0076_credential_bh_sync_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='bh_sync_done',
            field=models.BooleanField(default=False),
        ),
    ]
