# Generated by Django 4.2.7 on 2023-12-04 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0077_context_bh_sync_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='context',
            name='bh_sync_done',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='bh_sync_done',
        ),
    ]
