# Generated by Django 5.0.7 on 2024-07-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0079_alter_credential_hash_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedevent',
            name='raw_evidence',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
