# Generated by Django 5.1 on 2024-10-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0081_alter_webhook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='raw_evidence',
            field=models.TextField(blank=True, null=True),
        ),
    ]
