# Generated by Django 5.1 on 2024-10-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0082_alter_event_raw_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedevent',
            name='raw_evidence',
            field=models.TextField(blank=True, null=True),
        ),
    ]
