# Generated by Django 5.2 on 2025-05-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0083_alter_importedevent_raw_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='hash',
            field=models.CharField(blank=True, db_collation='nocase', help_text='A hashed version of the secret, in a form usable by hashcat', max_length=10000, null=True),
        ),
    ]
