# Generated by Django 6.0.3 on 2026-03-20 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('event_tracker', '0085_event_timestamp_end_after_timestamp_start'), ('event_tracker', '0086_alter_context_host_alter_context_process_and_more')]

    dependencies = [
        ('event_tracker', '0084_alter_credential_hash'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('timestamp_end__isnull', True), ('timestamp_end__gte', models.F('timestamp')), _connector='OR'), name='timestamp_end_after_timestamp_start'),
        ),
        migrations.AlterField(
            model_name='event',
            name='outcome',
            field=models.CharField(blank=True, default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='raw_evidence',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterConstraint(
            model_name='event',
            name='timestamp_end_after_timestamp_start',
            constraint=models.CheckConstraint(condition=models.Q(('timestamp_end__isnull', True), ('timestamp_end__gte', models.F('timestamp')), _connector='OR'), name='timestamp_end_after_timestamp_start', violation_error_message='Timestamp End can not be before Timestamp'),
        ),
    ]
